### ISSUE TITLE
block2-mpi installation on M1 Mac

### ISSUE THREAD

**Issue by KAtalar** [block-hczhai/block2-preview#69]
Hi there,

I am having issues installing the mpi version of block2 on my M1 Mac even though I can do it for the openMP only version.

It looks like it might be due to MKL not finding MPI compilers. I tried setting CMAKE_CXX_COMPILER, MPI_CXX_COMPILER and MPI_C_COMPILER as environment variables or use different python versions but it doesn't solve it. The errors are attached below. Any suggestions?

Many thanks,
Kem

❯ pip install block2-mpi
Collecting block2-mpi
  Using cached block2-mpi-0.5.2.tar.gz (1.0 MB)
  Preparing metadata (setup.py) ... done
Collecting mkl==2021.4
  Using cached mkl-2021.4.0-py2.py3-none-macosx_10_15_x86_64.macosx_11_0_x86_64.whl (186.4 MB)
Collecting mkl-include
  Using cached mkl_include-2023.2.1-py2.py3-none-macosx_10_15_x86_64.macosx_11_0_x86_64.whl (1.1 MB)
Collecting intel-openmp
  Using cached intel_openmp-2023.2.0-py2.py3-none-macosx_10_15_x86_64.macosx_11_0_x86_64.whl (758 kB)
Requirement already satisfied: numpy in /opt/anaconda3/lib/python3.9/site-packages (from block2-mpi) (1.21.5)
Collecting cmake>=3.19
  Using cached cmake-3.27.7-py2.py3-none-macosx_10_10_universal2.macosx_10_10_x86_64.macosx_11_0_arm64.macosx_11_0_universal2.whl (47.4 MB)
Requirement already satisfied: scipy in /opt/anaconda3/lib/python3.9/site-packages (from block2-mpi) (1.7.3)
Requirement already satisfied: psutil in /opt/anaconda3/lib/python3.9/site-packages (from block2-mpi) (5.9.0)
Collecting pybind11<=2.10.1
  Using cached pybind11-2.10.1-py3-none-any.whl (216 kB)
Collecting intel-openmp
  Using cached intel_openmp-2021.4.0-py2.py3-none-macosx_10_15_x86_64.macosx_11_0_x86_64.whl (1.3 MB)
Collecting tbb==2021.*
  Using cached tbb-2021.10.0-py2.py3-none-macosx_10_15_x86_64.macosx_11_0_x86_64.whl (640 kB)
Building wheels for collected packages: block2-mpi
  Building wheel for block2-mpi (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [120 lines of output]
      running bdist_wheel
      running build
      running build_ext
      cmake version 3.27.8

      CMake suite maintained and supported by Kitware (kitware.com/cmake).

      Python3:  /opt/anaconda3/bin/python
      Build Dir:  build/temp.macosx-10.9-x86_64-cpython-39
      CMake Deprecation Warning at CMakeLists.txt:1 (CMAKE_MINIMUM_REQUIRED):
        Compatibility with CMake < 3.5 will be removed from a future version of
        CMake.

        Update the VERSION argument <min> value or use a ...<max> suffix to tell
        CMake that the project does not need compatibility with older versions.

      -- The C compiler identification is AppleClang 15.0.0.15000040
      -- The CXX compiler identification is GNU 11.2.0
      -- Detecting C compiler ABI info
      -- Detecting C compiler ABI info - done
      -- Check for working C compiler: /opt/homebrew/bin/mpicc - skipped
      -- Detecting C compile features
      -- Detecting C compile features - done
      -- Checking whether CXX compiler has -isysroot
      -- Checking whether CXX compiler has -isysroot - yes
      -- Checking whether CXX compiler supports OSX deployment target flag
      -- Checking whether CXX compiler supports OSX deployment target flag - yes
      -- Detecting CXX compiler ABI info
      -- Detecting CXX compiler ABI info - done
      -- Check for working CXX compiler: /opt/local/bin/g++ - skipped
      -- Detecting CXX compile features
      -- Detecting CXX compile features - done
      CMake Warning (dev) at CMakeLists.txt:38 (FIND_PACKAGE):
        Policy CMP0148 is not set: The FindPythonInterp and FindPythonLibs modules
        are removed.  Run "cmake --help-policy CMP0148" for policy details.  Use
        the cmake_policy command to set the policy and suppress this warning.

      This warning is for project developers.  Use -Wno-dev to suppress it.

      -- Found PythonInterp: /usr/bin/python3 (found version "3.9.6")
      CMake Warning (dev) at CMakeLists.txt:44 (FIND_PACKAGE):
        Policy CMP0148 is not set: The FindPythonInterp and FindPythonLibs modules
        are removed.  Run "cmake --help-policy CMP0148" for policy details.  Use
        the cmake_policy command to set the policy and suppress this warning.

      This warning is for project developers.  Use -Wno-dev to suppress it.

      -- Found PythonLibs: /Applications/Xcode.app/Contents/Developer/Library/Frameworks/python3.framework (found suitable version "3.9.6", minimum required is "3.9")
      -- PYTHONLIBS_VERSION_STRING_SHORT = 3.9
      Traceback (most recent call last):
        File "<string>", line 1, in <module>
      ModuleNotFoundError: No module named 'pybind11'
      -- PROJECT_NAME = block2
      -- PYTHON_VERSION_MAJOR = 3
      -- PYTHON_VERSION_MINOR = 9
      -- PYTHON_LIBRARIES = /Applications/Xcode.app/Contents/Developer/Library/Frameworks/python3.framework
      -- PYTHON_EXECUTABLE = /usr/bin/python3
      -- PYTHON_EXECUTABLE_HINT = /opt/anaconda3/bin/python
      -- PYTHON_INCLUDE_DIRS = /Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Headers
      -- PYLIB_SUFFIX = .cpython-39-darwin.so
      -- PYBIND_INCLUDE_DIRS =
      -- BUILD_LIB = ON
      -- BUILD_CLIB = OFF
      g++: warning: could not understand version 14.00.00
      -- MKL_INCLUDE_DIR = MKL_INCLUDE_DIR-NOTFOUND
      -- MKL_LIBS = MKL_LIB_LP-NOTFOUND;MKL_LIB_CORE-NOTFOUND;MKL_LIB_GT-NOTFOUND;/opt/local/lib/gcc11/libgomp.dylib
      -- Could NOT find MPI_C (missing: MPI_C_WORKS)
      -- Could NOT find MPI_CXX (missing: MPI_CXX_WORKS)
      -- Could NOT find MPI (missing: MPI_C_FOUND MPI_CXX_FOUND)
      CMake Error at CMakeLists.txt:647 (MESSAGE):
        MPI not found.  Make sure CMAKE_CXX_COMPILER, MPI_CXX_COMPILER and
        MPI_C_COMPILER are set.

      -- Configuring incomplete, errors occurred!
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/mq/dzxh64p92g53p2cnqrj7tkv80000gn/T/pip-install-oqp19zql/block2-mpi_2439c0dda01f4d41b61f122bb6d1145f/setup.py", line 151, in <module>
          setup(
        File "/opt/anaconda3/lib/python3.9/site-packages/setuptools/__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File "/opt/anaconda3/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/opt/anaconda3/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/opt/anaconda3/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 968, in run_commands
          self.run_command(cmd)
        File "/opt/anaconda3/lib/python3.9/site-packages/setuptools/dist.py", line 1217, in run_command
          super().run_command(command)
        File "/opt/anaconda3/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
          cmd_obj.run()
        File "/opt/anaconda3/lib/python3.9/site-packages/wheel/bdist_wheel.py", line 299, in run
          self.run_command('build')
        File "/opt/anaconda3/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 319, in run_command
          self.distribution.run_command(command)
        File "/opt/anaconda3/lib/python3.9/site-packages/setuptools/dist.py", line 1217, in run_command
          super().run_command(command)
        File "/opt/anaconda3/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
          cmd_obj.run()
        File "/opt/anaconda3/lib/python3.9/site-packages/setuptools/_distutils/command/build.py", line 132, in run
          self.run_command(cmd_name)
        File "/opt/anaconda3/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 319, in run_command
          self.distribution.run_command(command)
        File "/opt/anaconda3/lib/python3.9/site-packages/setuptools/dist.py", line 1217, in run_command
          super().run_command(command)
        File "/opt/anaconda3/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
          cmd_obj.run()
        File "/opt/anaconda3/lib/python3.9/site-packages/setuptools/command/build_ext.py", line 84, in run
          _build_ext.run(self)
        File "/opt/anaconda3/lib/python3.9/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
          _build_ext.build_ext.run(self)
        File "/opt/anaconda3/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 346, in run
          self.build_extensions()
        File "/private/var/folders/mq/dzxh64p92g53p2cnqrj7tkv80000gn/T/pip-install-oqp19zql/block2-mpi_2439c0dda01f4d41b61f122bb6d1145f/setup.py", line 122, in build_extensions
          subprocess.check_call(
        File "/opt/anaconda3/lib/python3.9/subprocess.py", line 373, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['cmake', '/private/var/folders/mq/dzxh64p92g53p2cnqrj7tkv80000gn/T/pip-install-oqp19zql/block2-mpi_2439c0dda01f4d41b61f122bb6d1145f', '-DCMAKE_BUILD_TYPE=Release', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=/private/var/folders/mq/dzxh64p92g53p2cnqrj7tkv80000gn/T/pip-install-oqp19zql/block2-mpi_2439c0dda01f4d41b61f122bb6d1145f/build/lib.macosx-10.9-x86_64-cpython-39', '-DCMAKE_ARCHIVE_OUTPUT_DIRECTORY_RELEASE=build/temp.macosx-10.9-x86_64-cpython-39', '-DPYTHON_EXECUTABLE_HINT=/opt/anaconda3/bin/python', '-DUSE_MKL=ON', '-DMPI=ON', '-DBUILD_LIB=ON', '-DLARGE_BOND=ON', '-DUSE_KSYMM=OFF', '-DUSE_COMPLEX=ON', '-DUSE_SINGLE_PREC=ON', '-DUSE_SG=ON', '-DUSE_SANY=ON']' returned non-zero exit status 1.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for block2-mpi
  Running setup.py clean for block2-mpi
Failed to build block2-mpi
Installing collected packages: tbb, mkl-include, intel-openmp, cmake, pybind11, mkl, block2-mpi
  Attempting uninstall: tbb
    Found existing installation: TBB 0.2
ERROR: Cannot uninstall 'TBB'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.

**Comment by hczhai** [comment]
Hi, thanks for your interest in using ``block2``.

First of all, the MPI parallelization will always be less efficient than openMP, and in M1 Mac you only have one "node", so there is no need to install the MPI version. This is also why we do not provide precompiled binary package for ``block2-mpi`` on macOS. If you have a good reason to use the MPI version on macOS, please let me know.

Nevertheless, if you compile from source, this should still be possible. First, please do not use ``pip install block2-mpi`` since in this case it is hard to control environment variables. Instead, you can follow the procedure in https://block2.readthedocs.io/en/latest/user/installation.html#manual-installation to build manually (starting from ``git clone ...`` and ``mkdir build`` etc.) In particular, we need the following options for your case:

1. ``-DUSE_MKL=OFF`` since there is no MKL on macOS with M1 CPU.
2. ``-DARCH_ARM64=ON`` to build for the arm64 M1 CPU in macOS.
3. ``-DBUILD_LIB=ON -DLARGE_BOND=ON -DMPI=ON`` as normal.

You can use something like ``CC=mpicc CXX=mpic++ cmake .. -D...`` to help ``cmake`` find the correct compiler. If you have further problems please let me know.

**Comment by hczhai** [comment]
Hi, thanks for the feedback. As shown in your ``cmake`` output, the reason for ``Could NOT find MPI_CXX`` is ``missing: MPI_CXX_WORKS``. Namely, ``cmake`` thinks that your ``/opt/homebrew/bin/mpic++`` is not working. So the next thing to do is to manually check your MPI C++ compiler and figure out why it is not working.

You can prepare the following C++ code, saved as ``main.cpp``:

```c++
#include <iostream>
#include "mpi.h"
using namespace std;
int main() {
    MPI_Init(nullptr, nullptr);
    int _rank, _size;
    MPI_Comm_rank(MPI_COMM_WORLD, &_rank);
    MPI_Comm_size(MPI_COMM_WORLD, &_size);
    cout << "Rank = " << _rank << " / " << _size << endl;
    MPI_Finalize();
    return 0;
}
```

You can compile this code to generate the executable ``main.x``:
```bash
mpic++ -O3 main.cpp -o main.x
```

Then you can run the executable using ``mpirun``:
```bash
mpirun -n 4 ./main.x
```

You may see some problems/error messages when you do the above. Make sure you solve the problems, so that the ``mpic++`` compiler is working properly, and then you can go back to build ``block2``.
