### ISSUE TITLE
Segmentation fault when sampling determinants

### ISSUE THREAD

**Issue by davidsousarj** [block-hczhai/block2-preview#94]
Hi, I am revisiting the calculations from Issue #52 . I am trying to do the same thing (sampling the CI determinant coefficients) for a bigger system, but the program is not able to perform the calculation, it always gets a segmentation fault.

Here is the input file, it is almost the same as the one suggested in the Issue #52, but it is for the FeSe molecule: [Input file](https://mega.nz/file/0hcDCYaD#JMc5djT44q_AO5V854a34V8j2aVVJaXC0TAKlbJuVmA)

Error message:
```
ERROR:  /home/david/.local/bin/block2main dmrg.conf > dmrg.out 2>&1

ERROR:  /home/david/.local/bin/block2main dmrg.conf > dmrg.out 2>&1
Ttotal =      0.001

Environment initialization | Nsites =     9 | Center =     0
 INIT-R <-- Site =    7 ..  Bmem =   288 B Rmem =   288 B T = 0.00
 INIT-R <-- Site =    6 ..  Bmem =   288 B Rmem = 4.19 KB T = 0.00
 INIT-R <-- Site =    5 ..  Bmem = 4.19 KB Rmem = 55.0 KB T = 0.00
 INIT-R <-- Site =    4 ..  Bmem = 55.0 KB Rmem =  540 KB T = 0.00
 INIT-R <-- Site =    3 ..  Bmem =  540 KB Rmem = 4.26 MB T = 0.01
 INIT-R <-- Site =    2 ..  Bmem = 4.26 MB Rmem = 16.7 MB T = 0.05
 INIT-R <-- Site =    1 ..  Bmem = 16.7 MB Rmem = 11.9 MB T = 0.06
 INIT-R <-- Site =    0 ..  Bmem = 11.9 MB Rmem = 5.74 MB T = 0.03
Time init sweep =        0.149 | MaxBmem = 16.7 MB | MaxRmem = 11.9 MB
 | Tread = 0.000 | Twrite = 0.045 | Tfpread = 0.000 | Tfpwrite = 0.044 | data = 39.1 MB | cpsd = 29.7 MB | Tasync = 0.000


Expectation | Direction =  forward | BRA bond dimension =  349 | KET bond dimension =  349
 --> Site =    0 .. Nterms =          723 Error =  0.000000000000/ 0.000000000000 FLOPS = 1.54e+09 Tmult = 0.00 T = 0.01
 --> Site =    1 .. Nterms =         1607 Error =  0.000000000000/ 0.000000000000 FLOPS = 2.20e+09 Tmult = 0.00 T = 0.01
 --> Site =    2 .. Nterms =         1999 Error =  0.000000000000/ 0.000000000000 FLOPS = 2.46e+09 Tmult = 0.01 T = 0.03
 --> Site =    3 .. Nterms =         2007 Error =  0.000000000000/ 0.000000000000 FLOPS = 3.57e+09 Tmult = 0.00 T = 0.01
 --> Site =    4 .. Nterms =         1739 Error =  0.000000000000/ 0.000000000000 FLOPS = 2.42e+09 Tmult = 0.00 T = 0.01
 --> Site =    5 .. Nterms =         1303 Error =  0.000000000000/ 0.000000000000 FLOPS = 1.04e+09 Tmult = 0.00 T = 0.01
 --> Site =    6 .. Nterms =          807 Error =  0.000000000000/ 0.000000000000 FLOPS = 2.88e+08 Tmult = 0.00 T = 0.01
 --> Site =    7 .. Nterms =          426 Error =  0.000000000000/ 0.000000000000 FLOPS = 2.11e+07 Tmult = 0.00 T = 0.00
 --> Site =    8 .. Nterms =            0 Error =  0.000000000000/ 0.000000000000 FLOPS = 0.00e+00 Tmult = 0.00 T = 0.00
Time elapsed =      0.075
Time sweep =        0.075 | 40.7 MFLOP/SWP
 | Dmem = 16.8 MB (0%) | Imem = 2.70 KB (62%) | Hmem = 16.8 MB | MaxBmem = 750 KB | MaxRmem = 835 KB
 | Tread = 0.032 | Twrite = 0.003 | Tfpread = 0.032 | Tfpwrite = 0.003 | data = 2.57 MB | cpsd = 1.94 MB | Tasync = 0.000
 | Trot = 0.009 | Tctr = 0.000 | Tint = 0.000 | Tmid = 0.000 | Tdctr = 0.000 | Tdiag = 0.000 | Tinfo = 0.001
 | Teff = 0.037 | Texpt = 0.018 | Tblk = 0.075 | Tmve = 0.000

NPDM Sorting | Nsites =     9 | Nmaxops =  4 | DotSite = 0 | SymbolFree = T | Compressed = T | LowMem = F | Mem = 154 KB
 Site =     0 ..  T = 0.000
 Site =     1 ..  T = 0.000
 Site =     2 ..  T = 0.000
 Site =     3 ..  T = 0.000
 Site =     4 ..  T = 0.000
 Site =     5 ..  T = 0.000
 Site =     6 ..  T = 0.000
 Site =     7 ..  T = 0.000
Ttotal =      0.001

----- root =  29 /  30 -----
npdm string = ['ccdd', 'cCDd', 'CCDD']

Build NPDM MPO | Nsites =     9 | Nmaxops =  4 | SymbolFree = T | Cutoff = 0.00e+00
 Site =     0 /     9 .. L =       26 R =        1 M =            0 Tmid = 0.000 T = 0.000
 Site =     1 /     9 .. L =       74 R =      561 M =         1251 Tmid = 0.000 T = 0.000
 Site =     2 /     9 .. L =      122 R =      435 M =         2997 Tmid = 0.000 T = 0.000
 Site =     3 /     9 .. L =      170 R =      325 M =         3771 Tmid = 0.000 T = 0.000
 Site =     4 /     9 .. L =      218 R =      231 M =         3789 Tmid = 0.000 T = 0.000
 Site =     5 /     9 .. L =      266 R =      153 M =         3267 Tmid = 0.000 T = 0.000
 Site =     6 /     9 .. L =      314 R =       91 M =         2421 Tmid = 0.000 T = 0.000
 Site =     7 /     9 .. L =      362 R =       45 M =         1467 Tmid = 0.000 T = 0.000
 Site =     8 /     9 .. L =        1 R =       26 M =          720 Tmid = 0.000 T = 0.000
Ttotal =      0.001

Environment initialization | Nsites =     9 | Center =     0
 INIT-R <-- Site =    7 ..  Bmem =   288 B Rmem =   288 B T = 0.00
 INIT-R <-- Site =    6 ..  Bmem =   288 B Rmem = 4.19 KB T = 0.00
 INIT-R <-- Site =    5 ..  Bmem = 4.19 KB Rmem = 55.0 KB T = 0.00
 INIT-R <-- Site =    4 ..  Bmem = 55.0 KB Rmem =  540 KB T = 0.00
 INIT-R <-- Site =    3 ..  Bmem =  540 KB Rmem = 4.26 MB T = 0.01
 INIT-R <-- Site =    2 ..  Bmem = 4.26 MB Rmem = 16.7 MB T = 0.04
 INIT-R <-- Site =    1 ..  Bmem = 16.7 MB Rmem = 11.9 MB T = 0.06
 INIT-R <-- Site =    0 ..  Bmem = 11.9 MB Rmem = 5.74 MB T = 0.03
Time init sweep =        0.148 | MaxBmem = 16.7 MB | MaxRmem = 11.9 MB
 | Tread = 0.000 | Twrite = 0.045 | Tfpread = 0.000 | Tfpwrite = 0.045 | data = 39.1 MB | cpsd = 29.7 MB | Tasync = 0.000


Expectation | Direction =  forward | BRA bond dimension =  349 | KET bond dimension =  349
 --> Site =    0 .. Nterms =          723 Error =  0.000000000000/ 0.000000000000 FLOPS = 1.54e+09 Tmult = 0.00 T = 0.01
 --> Site =    1 .. Nterms =         1607 Error =  0.000000000000/ 0.000000000000 FLOPS = 2.18e+09 Tmult = 0.00 T = 0.01
 --> Site =    2 .. Nterms =         1999 Error =  0.000000000000/ 0.000000000000 FLOPS = 2.40e+09 Tmult = 0.01 T = 0.03
 --> Site =    3 .. Nterms =         2007 Error =  0.000000000000/ 0.000000000000 FLOPS = 3.59e+09 Tmult = 0.00 T = 0.01
 --> Site =    4 .. Nterms =         1739 Error =  0.000000000000/ 0.000000000000 FLOPS = 2.40e+09 Tmult = 0.00 T = 0.01
 --> Site =    5 .. Nterms =         1303 Error =  0.000000000000/ 0.000000000000 FLOPS = 9.02e+08 Tmult = 0.00 T = 0.01
 --> Site =    6 .. Nterms =          807 Error =  0.000000000000/ 0.000000000000 FLOPS = 2.34e+08 Tmult = 0.00 T = 0.01
 --> Site =    7 .. Nterms =          426 Error =  0.000000000000/ 0.000000000000 FLOPS = 2.55e+07 Tmult = 0.00 T = 0.00
 --> Site =    8 .. Nterms =            0 Error =  0.000000000000/ 0.000000000000 FLOPS = 0.00e+00 Tmult = 0.00 T = 0.00
Time elapsed =      0.076
Time sweep =        0.076 | 40.7 MFLOP/SWP
 | Dmem = 16.8 MB (0%) | Imem = 2.70 KB (62%) | Hmem = 16.8 MB | MaxBmem = 682 KB | MaxRmem = 820 KB
 | Tread = 0.031 | Twrite = 0.003 | Tfpread = 0.031 | Tfpwrite = 0.003 | data = 2.43 MB | cpsd = 1.82 MB | Tasync = 0.000
 | Trot = 0.009 | Tctr = 0.000 | Tint = 0.000 | Tmid = 0.000 | Tdctr = 0.000 | Tdiag = 0.000 | Tinfo = 0.001
 | Teff = 0.037 | Texpt = 0.019 | Tblk = 0.075 | Tmve = 0.000

NPDM Sorting | Nsites =     9 | Nmaxops =  4 | DotSite = 0 | SymbolFree = T | Compressed = T | LowMem = F | Mem = 154 KB
 Site =     0 ..  T = 0.000
 Site =     1 ..  T = 0.000
 Site =     2 ..  T = 0.000
 Site =     3 ..  T = 0.000
 Site =     4 ..  T = 0.000
 Site =     5 ..  T = 0.000
 Site =     6 ..  T = 0.000
 Site =     7 ..  T = 0.000
Ttotal =      0.001

Segmentation fault (core dumped)
Traceback (most recent call last):
  File "/home/david/FeSe_github.py", line 84, in <module>
    
  File "/home/david/.local/lib/python3.10/site-packages/pyscf/mcscf/casci.py", line 963, in kernel
    kernel(self, mo_coeff, ci0=ci0, verbose=log)
  File "/home/david/.local/lib/python3.10/site-packages/pyscf/mcscf/casci.py", line 593, in kernel
    e_tot, fcivec = casci.fcisolver.kernel(h1eff, eri_cas, ncas, nelecas,
  File "/home/david/.local/lib/python3.10/site-packages/pyscf/dmrgscf/dmrgci.py", line 736, in kernel
    executeBLOCK(self)
  File "/home/david/.local/lib/python3.10/site-packages/pyscf/dmrgscf/dmrgci.py", line 954, in executeBLOCK
    raise err
  File "/home/david/.local/lib/python3.10/site-packages/pyscf/dmrgscf/dmrgci.py", line 949, in executeBLOCK
    check_call(cmd, cwd=DMRGCI.runtimeDir, shell=True)
  File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command ' /home/david/.local/bin/block2main dmrg.conf > dmrg.out 2>&1' returned non-zero exit status 139.
```

**Comment by hczhai** [comment]
The ``pyscf/dmrgscf`` interface does not support the computation of determinant coefficients **for nroots larger than 1**. But in your script you have 30 roots. If you want to do this, you may use the ``driver.split_mps`` method provided in the Python interface to split the state-averaged MPS, and then perform the computation of determinant coefficients for each individual state (root). The script given in https://github.com/block-hczhai/block2-preview/issues/93#issuecomment-2094064455 is an example for this.

**Comment by hczhai** [comment]
The version 0.5.1 is too old which does not support this feature. You may upgrade to the most recent version using

```
python3 -m pip uninstall block2
python3 -m pip install block2==0.5.3rc11 --extra-index-url=https://block-hczhai.github.io/block2-preview/pypi/
```

Note that the new version additionally supports new Python versions 3.11 and 3.12.
